# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '44 7 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has been inactive for a while. If this is critical, contact me at sidgames5@mlgland.net'
        stale-pr-message: 'This PR has been inactive for a while. If this is critical, contact me at sidgames5@mlgland.net'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
